//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachersReviewSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schools
    {
        public schools()
        {
            this.subjects = new HashSet<subjects>();
        }
    
        public int schoolID { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<subjects> subjects { get; set; }
    }
}
