//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachersReviewSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subjects
    {
        public subjects()
        {
            this.employee = new HashSet<employee>();
            this.studentsDetail = new HashSet<studentsDetail>();
        }
    
        public int subjectID { get; set; }
        public int schoolID { get; set; }
        public string name { get; set; }
        public int year { get; set; }
    
        public virtual ICollection<employee> employee { get; set; }
        public virtual schools schools { get; set; }
        public virtual ICollection<studentsDetail> studentsDetail { get; set; }
    }
}
